
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: ABCabc123


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl